# Generated by Django 5.0 on 2025-05-09 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='جديد'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='عرض خاص'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutiqe.color', verbose_name='اللون')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='boutiqe.product', verbose_name='المنتج')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutiqe.size', verbose_name='المقاس')),
            ],
            options={
                'verbose_name': 'تنوع المنتج',
                'verbose_name_plural': 'تنوعات المنتج',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
