# Generated by Django 5.0 on 2025-05-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0003_product_is_new_product_is_sale_product_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخصم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الخصم')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'قيمة ثابتة')], default='percentage', max_length=20, verbose_name='نوع الخصم')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='boutiqe.category', verbose_name='الفئات')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='boutiqe.product', verbose_name='المنتجات')),
            ],
            options={
                'verbose_name': 'خصم',
                'verbose_name_plural': 'الخصومات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendingCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المجموعة')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='وصف المجموعة')),
                ('image', models.ImageField(upload_to='collections/', verbose_name='صورة المجموعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('products', models.ManyToManyField(related_name='collections', to='boutiqe.product', verbose_name='المنتجات')),
            ],
            options={
                'verbose_name': 'مجموعة رائجة',
                'verbose_name_plural': 'المجموعات الرائجة',
                'ordering': ['-created_at'],
            },
        ),
    ]
