# Generated by Django 5.0 on 2025-05-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0004_discount_trendingcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discounts/', verbose_name='صورة الخصم'),
        ),
    ]
