# Generated by Django 5.0 on 2025-05-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0005_discount_image'),
        ('boutiqe', 'add_slug_to_discount'),
    ]

    operations = [
    ]
