# Generated by Django 5.0 on 2025-05-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0006_merge_0005_discount_image_add_slug_to_discount'),
    ]

    operations = [
    ]
