# Generated by Django 5.0 on 2025-05-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0005_alter_orderitem_created_at'),
    ]

    operations = [
        # This migration originally attempted to recreate ContactInfo, which has already been
        # created in 0004. We leave this as a no-op to avoid 'table already exists' errors.
    ]
