# Generated by Django 5.0 on 2025-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0008_fix_orderitem_color_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendingcollection',
            options={'ordering': ['order_position', '-created_at'], 'verbose_name': 'مجموعة رائجة', 'verbose_name_plural': 'المجموعات الرائجة'},
        ),
        migrations.AddField(
            model_name='trendingcollection',
            name='order_position',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
    ]
