# Generated by Django 5.0 on 2025-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0009_alter_trendingcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['order_position', '-created_at'], 'verbose_name': 'خصم', 'verbose_name_plural': 'الخصومات'},
        ),
        migrations.AddField(
            model_name='discount',
            name='order_position',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
    ]
