# Generated by Django 5.0 on 2025-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqe', '0010_alter_discount_options_discount_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discounts/', verbose_name='صورة الخصم'),
        ),
    ]
